const products = [
  {
    id: 1,
    name: "Espresso",
    category: "espresso",
    price: 35000,
    rating: 4.5,
    image: "/espresso-coffee-cup.png",
    description: "Cà phê đen đậm đà, khởi đầu hoàn hảo cho ngày mới",
    specs: "Kích thước: 30ml | Nhiệt độ: 85°C | Loại hạt: Đặc biệt",
    bestseller: true,
  },
  {
    id: 2,
    name: "Cappuccino",
    category: "milk",
    price: 45000,
    rating: 4.8,
    image: "/cappuccino-coffee.png",
    description: "Cà phê sữa hài hòa giữa Espresso và sữa nóng với lớp foam mềm mịn",
    specs: "Kích thước: 250ml | Nhiệt độ: 75°C | Tỷ lệ: 1:1:1",
    new: true,
  },
  {
    id: 3,
    name: "Latte",
    category: "milk",
    price: 50000,
    rating: 4.7,
    image: "/latte-coffee.jpg",
    description: "Cà phê sữa mặn mà, nhẹ nhàng, thích hợp cho những ai yêu thích vị sữa",
    specs: "Kích thước: 300ml | Nhiệt độ: 65°C | Tỷ lệ: 1:3:1",
    bestseller: true,
  },
  {
    id: 4,
    name: "Americano",
    category: "espresso",
    price: 40000,
    rating: 4.4,
    image: "/americano-coffee.png",
    description: "Espresso pha nước nóng, cùng vị đắng nhẹ của cà phê nguyên chất",
    specs: "Kích thước: 200ml | Nhiệt độ: 80°C | Tỷ lệ: 1:3",
    new: true,
  },
  {
    id: 5,
    name: "Iced Latte",
    category: "cold",
    price: 55000,
    rating: 4.6,
    image: "/iced-latte-coffee.jpg",
    description: "Latte lạnh mát, hoàn hảo cho những ngày hè nóng bức",
    specs: "Kích thước: 300ml | Nhiệt độ: Lạnh | Loại đá: Cấp 3",
    bestseller: true,
  },
  {
    id: 6,
    name: "Iced Americano",
    category: "cold",
    price: 45000,
    rating: 4.5,
    image: "/iced-americano.png",
    description: "Americano lạnh, giải khát trong những lúc bận rộn",
    specs: "Kích thước: 250ml | Nhiệt độ: Lạnh | Loại đá: Cấp 3",
    new: true,
  },
  {
    id: 7,
    name: "Macchiato",
    category: "espresso",
    price: 48000,
    rating: 4.6,
    image: "/macchiato-coffee.jpg",
    description: "Espresso 'đánh dấu' bằng một chút sữa, cân bằng giữa đắng và mát",
    specs: "Kích thước: 120ml | Nhiệt độ: 80°C | Tỷ lệ: 1:0.5",
    bestseller: true,
  },
  {
    id: 8,
    name: "Mocha",
    category: "milk",
    price: 60000,
    rating: 4.9,
    image: "/mocha-coffee.jpg",
    description: "Cà phê cacao hòa quyện, tuyệt vời cho những ai yêu thích vị cacao",
    specs: "Kích thước: 300ml | Nhiệt độ: 70°C | Thành phần: Cacao, sữa, cà phê",
    new: true,
  },
]
